In [32]:
import numpy as np
import pandas as pd

# Question 1: NumPy Fundamentals

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [12]:
np.random.seed(42)
feature_vector = np.arange(5, 17)
feature_matrix = np.random.randint(0, 10, size=(3, 4))

print('feature_vector:\n', feature_vector)
print('feature_matrix:\n', feature_matrix)
print('vector shape/ndim/size/dtype:', feature_vector.shape, feature_vector.ndim, feature_vector.size, feature_vector.dtype)
print('matrix shape/ndim/size/dtype:', feature_matrix.shape, feature_matrix.ndim, feature_matrix.size, feature_matrix.dtype)
print('matrix[1,2]:', feature_matrix[1, 2])
print('first row:', feature_matrix[0, :])
print('last column:', feature_matrix[:, -1])
print('top-right 2x2:\n', feature_matrix[:2, 2:4])
feature_vector_reshaped = feature_vector.reshape(4, 3)
print('reshaped vector shape:', feature_vector_reshaped.shape)
print('flattened matrix:', feature_matrix.flatten())
ones_matrix = np.ones((3, 4), dtype=int)
vertical_stack = np.vstack([feature_matrix, ones_matrix])
column_vector = np.array([[10], [20], [30]])
horizontal_stack = np.hstack([feature_matrix, column_vector])
print('vertical stack:\n', vertical_stack)
print('horizontal stack:\n', horizontal_stack)

feature_vector:
 [ 5  6  7  8  9 10 11 12 13 14 15 16]
feature_matrix:
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
vector shape/ndim/size/dtype: (12,) 1 12 int64
matrix shape/ndim/size/dtype: (3, 4) 2 12 int64
matrix[1,2]: 2
first row: [6 3 7 4]
last column: [4 6 7]
top-right 2x2:
 [[7 4]
 [2 6]]
reshaped vector shape: (4, 3)
flattened matrix: [6 3 7 4 6 9 2 6 7 4 3 7]
vertical stack:
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
horizontal stack:
 [[ 6  3  7  4 10]
 [ 6  9  2  6 20]
 [ 7  4  3  7 30]]


# Question 2: Numerical operations and preprocessing

In [17]:
np.random.seed(101)
scores = np.random.randint(50, 101, size=(15, 3))
means = scores.mean(axis=0).round(2)
stds = scores.std(axis=0)
max_third_exam = scores[:, 2].max()
student_means = scores.mean(axis=1).round(2)
curved_scores = scores.copy()
curved_scores[:, 0] += 5
normalized_scores = (scores - means) / stds

print('scores:\n', scores)
print('means:', means)
print('stds:', stds)
print('max_third_exam:', max_third_exam)
print('student_means:', student_means)
print('curved_scores:\n', curved_scores)
print('normalized means:', normalized_scores.mean(axis=0))
print('normalized stds:', normalized_scores.std(axis=0))

scores:
 [[81 61 67]
 [56 73 61]
 [97 59 63]
 [90 54 90]
 [78 50 96]
 [55 62 79]
 [90 99 69]
 [97 58 79]
 [84 94 58]
 [69 60 62]
 [81 93 73]
 [50 91 59]
 [97 58 86]
 [69 85 78]
 [57 60 89]]
means: [76.73 70.47 73.93]
stds: [15.91840305 16.38644426 12.01369589]
max_third_exam: 96
student_means: [69.67 63.33 73.   78.   74.67 65.33 86.   78.   78.67 63.67 82.33 66.67
 80.33 77.33 68.67]
curved_scores:
 [[ 86  61  67]
 [ 61  73  61]
 [102  59  63]
 [ 95  54  90]
 [ 83  50  96]
 [ 60  62  79]
 [ 95  99  69]
 [102  58  79]
 [ 89  94  58]
 [ 74  60  62]
 [ 86  93  73]
 [ 55  91  59]
 [102  58  86]
 [ 74  85  78]
 [ 62  60  89]]
normalized means: [ 0.0002094  -0.00020342  0.00027746]
normalized stds: [1. 1. 1.]


# Question3: Data filtering

In [22]:
high_mask = scores > 95
high_count = high_mask.sum()
high_performers_scores = scores[high_mask]
second_exam_mean_for_low_first = scores[scores[:, 0] <= 70, 1].mean().round(2)
pass_fail = scores.mean(axis=1) > 65
excellent_mask = np.all(scores >= 90, axis=1)
excellent_scores = scores[excellent_mask]

print('high_count:', high_count)
print('high_performers_scores:', high_performers_scores)
print('second_exam_mean_for_low_first:', second_exam_mean_for_low_first)
print('pass_fail:', pass_fail)
print('excellent_scores:', excellent_scores if len(excellent_scores) else 'No excellent students found')

high_count: 5
high_performers_scores: [97 96 99 97 97]
second_exam_mean_for_low_first: 71.83
pass_fail: [ True False  True  True  True  True  True  True  True False  True  True
  True  True  True]
excellent_scores: No excellent students found


# Question 4: Exploratory Data Analysis of the Titanic Dataset

In [28]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)
print('First 5 lines:\n',df.head())
print('info:\n',df.info())
print('describe:\n',df.describe())

survived = df['Survived']
selected_cols = df[['Pclass', 'Sex', 'Age']]
row_3 = df.loc[3]
first_5_3cols = df.iloc[:5, :3]
num_survived = df['Survived'].sum()
survivors = df[df['Survived'] == 1]
num_male_survivors = survivors[survivors['Sex'] == 'male'].shape[0]
first_class_age_over_50 = df[(df['Pclass'] == 1) & (df['Age'] > 50)]

print(type(survived))
print(selected_cols.head())
print(row_3)
print(first_5_3cols)
print(num_survived, num_male_survivors, first_class_age_over_50.shape[0])

First 5 lines:
    PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   N

# Question 5: Data Cleaning and Preprocessing

In [29]:
missing_counts = df.isnull().sum()
df_cleaned = df.drop(columns=['Cabin']).copy()
age_median = df_cleaned['Age'].median()
df_cleaned['Age'] = df_cleaned['Age'].fillna(age_median)
embarked_mode = df_cleaned['Embarked'].mode()[0]
df_cleaned['Embarked'] = df_cleaned['Embarked'].fillna(embarked_mode)
df_cleaned['Pclass'] = df_cleaned['Pclass'].astype('category')

print(missing_counts)
print(df_cleaned.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


# Question 6: Feature Engineering and Group Analysis

In [31]:
df_cleaned['FamilySize'] = df_cleaned['SibSp'] + df_cleaned['Parch']
df_cleaned['Title'] = df_cleaned['Name'].str.extract(r',\s*([^\.]+)\.', expand=False).str.strip()
sex_survival = df_cleaned.groupby('Sex')['Survived'].mean()
pclass_survival = df_cleaned.groupby('Pclass')['Survived'].mean()
pclass_sex_survival = df_cleaned.groupby(['Pclass', 'Sex'])['Survived'].mean()

def age_group(x):
    if x < 18:
        return 'Child'
    elif x <= 65:
        return 'Adult'
    return 'Senior'

df_cleaned['AgeGroup'] = df_cleaned['Age'].apply(age_group)
print(df_cleaned[['FamilySize', 'Title', 'AgeGroup']].head())
print(sex_survival)
print(pclass_survival)
print(pclass_sex_survival)

   FamilySize Title AgeGroup
0           1    Mr    Adult
1           1   Mrs    Adult
2           0  Miss    Adult
3           1   Mrs    Adult
4           0    Mr    Adult
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
Pclass  Sex   
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64


/tmp/ipykernel_6355/1272117557.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pclass_survival = df_cleaned.groupby('Pclass')['Survived'].mean()
/tmp/ipykernel_6355/1272117557.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pclass_sex_survival = df_cleaned.groupby(['Pclass', 'Sex'])['Survived'].mean()
